### ISSUE TITLE
Data Loading Issues

### ISSUE THREAD

**Issue by viciousAegis** [VijayLingam95/RethinkingLabelPoisoningForGNNs#1]
hello,
im trying to run the main file, however i believe to run it data has to already be downloaded. im getting the following missing file error:
```
../utils.py", line 31, in __init__
    self.dataset_data = pkl.load(open(osp.join(self.data_dir, self.name + ".pkl"), 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '../../final_data/datasets/cora_ml.pkl'
```

can you tell me the data format for the datasets? thanks!

**Comment by VijayLingam95** [comment]
Hi,

Thanks for the catch. You can download the datasets from here: https://github.com/VijayLingam95/PitfallsOfLabelPoisoningAttacksForGNNs/blob/main/PitfallsOfLabelPoisoningAttacksData.zip

I will update the repo with any missing datasets soon.
